name = "StrideArrays"
uuid = "d1fa6d79-ef01-42a6-86c9-f7c551f8593b"
authors = ["Chris Elrod <elrodc@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
